[theme]
base = "light"
primaryColor = "#0B7468"
backgroundColor = "#EEF3F5"
secondaryBackgroundColor = "#ffffff"
textColor = "#163744"
font = "sans serif"

[server]
maxUploadSize = 10

[browser]
gatherUsageStats = false
